import os
import json
import streamlit as st
from openai import OpenAI
from utils.parser import parse_config

# ----------- LOAD API KEY (Streamlit Cloud or Local .env) -----------
api_key = st.secrets.get("OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

# ---------------- UI SETTINGS ----------------
st.set_page_config(page_title="NetDoc AI", layout="wide")

# ---------------- LOGO + TITLE ----------------
st.image("logo.png", width=180)
st.title("⚡ NetDoc AI — Autonomous Network Documentation Engine")
st.write("Upload Cisco switch/router configs and generate structured documentation automatically.")

# ---------------- FILE UPLOAD ----------------
uploaded_files = st.file_uploader(
    "Upload one or more config files",
    type=["txt", "cfg", "log"],
    accept_multiple_files=True
)

# ---------------- MAIN PROCESS ----------------
if uploaded_files and st.button("Generate Report"):
    combined = ""
    for f in uploaded_files:
        combined += f"\n\n# FILE: {f.name}\n"
        combined += f.read().decode("utf-8")

    with st.spinner("Processing your configs…"):
        result = parse_config(combined)

    st.success("Report generated successfully!")

    # ---------------- TABS ----------------
    tab1, tab2 = st.tabs(["📄 Documentation", "🔧 Raw JSON"])

    # -------- TAB 1: Documentation --------
    with tab1:
        st.subheader("📄 Parsed Network Documentation")
        st.write("Below is the structured documentation generated by NetDoc AI:")
        st.json(result)

    # -------- TAB 2: Raw JSON --------
    with tab2:
        st.subheader("🔧 Full JSON Output")
        st.code(json.dumps(result, indent=2), language="json")

    # ---------------- DOWNLOAD OPTIONS ----------------
    st.download_button(
        label="📥 Download JSON",
        data=json.dumps(result, indent=2),
        file_name="netdoc_output.json",
        mime="application/json"
    )

    st.info("PDF, DOCX, HTML export + Security Audit + Topology Diagram will be added in Step C-2.")
