import os
import json
import streamlit as st
from openai import OpenAI
from utils.parser import parse_config

st.set_page_config(page_title="NetDoc AI", layout="wide")

# ----------------- API KEY -----------------
api_key = st.secrets.get("OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=api_key)

# ----------------- BRANDING -----------------
LOGO_URL = "https://raw.githubusercontent.com/lokauday/Netdoc-agent/main/assets/logo.png"
FOOTER_TEXT = "Generated by NetDoc AI — Autonomous Network Documentation Engine"

# ----------------- UI HEADER -----------------
st.markdown(
    f"""
    <div style="text-align:center;">
        <img src="{LOGO_URL}" width="180"><br>
        <h1>⚡ NetDoc AI — Autonomous Network Documentation Engine</h1>
        <p>Upload configs → AI creates documentation, security audit, topology & exports.</p>
    </div>
    """,
    unsafe_allow_html=True,
)

# ----------------- FILE UPLOAD -----------------
uploaded_files = st.file_uploader(
    "Upload Your Config Files",
    type=["txt", "cfg", "log"],
    accept_multiple_files=True
)

if uploaded_files:
    combined = ""
    for f in uploaded_files:
        combined += f"\n\n# FILE: {f.name}\n"
        combined += f.read().decode("utf-8")

    with st.spinner("Analyzing configuration..."):
        result = parse_config(combined)

    # ----------------- TABS -----------------
    tab1, tab2, tab3, tab4 = st.tabs(
        ["📘 Documentation", "🛡 Security Audit", "🌐 Topology", "📤 Export"]
    )

    # ----------------- TAB 1: DOCUMENTATION -----------------
    with tab1:
        st.subheader("📘 Full AI Generated Documentation")
        st.json(result)

    # ----------------- TAB 2: SECURITY AUDIT (placeholder) -----------------
    with tab2:
        st.subheader("🛡 Security Audit Report")
        st.info("Security audit will appear here.")
        st.write("- Weak Passwords")
        st.write("- Disabled STP Guards")
        st.write("- VLAN Leaks / Misconfigurations")
        st.write("- Missing ACLs")
        st.write("- Outdated IOS")

    # ----------------- TAB 3: TOPOLOGY (placeholder) -----------------
    with tab3:
        st.subheader("🌐 Network Topology Diagram")
        st.info("AI-generated ASCII topology will appear here.")
        topology = result.get("ascii_topology", "")
        st.code(topology if topology else "No topology detected.")

    # ----------------- TAB 4: EXPORT (placeholders) -----------------
    with tab4:
        st.subheader("📤 Export Documentation")

        st.write("Exports coming soon:")
        st.write("• PDF Export")
        st.write("• DOCX Export")
        st.write("• HTML Export")

# ----------------- FOOTER -----------------
st.markdown(
    f"""
    <hr>
    <div style="text-align:center; opacity:0.6;">
        {FOOTER_TEXT}
    </div>
    """,
    unsafe_allow_html=True
)
